[platformio]
default_envs = round_voice

[env:round_voice]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
extra_scripts = pre:tools/usb_driver.py
board_build.f_cpu = 240000000L
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM=1
    -DCONFIG_SPIRAM_MODE_OCT=1
    -DCONFIG_SPIRAM_SPEED_80M=1
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_LOOP_STACK_SIZE=16384
lib_ldf_mode = deep
