"""63-tap Hamming low-pass for 48 kHz microphone input -> 16 kHz recognition."""
import math
from pathlib import Path

root = Path(__file__).resolve().parents[1]
count, cutoff = 63, 6500/48000
values = []
for i in range(count):
    x = i-(count-1)/2
    sinc = 2*cutoff if x == 0 else math.sin(2*math.pi*cutoff*x)/(math.pi*x)
    values.append(sinc*(.54-.46*math.cos(2*math.pi*i/(count-1))))
scale = sum(values)
text = '#pragma once\n// Generated by tools/make_mic_filter.py. Original mathematical coefficients.\n'
text += 'static constexpr float micFilter[63]={\n'
text += ',\n'.join(f'    {value/scale:.10f}f' for value in values)
text += '\n};\n'
(root/'include/mic_filter.h').write_text(text, encoding='utf-8')
