"""Generate one soft, rounded activation note; no samples or external sound assets."""
from pathlib import Path
import math
import struct
import wave
import shutil

ROOT = Path(__file__).resolve().parents[1]
RATE = 16000
LENGTH = 7680  # 480 ms


def samples():
    result = []
    for i in range(LENGTH):
        t = i / RATE
        attack = .5 - .5 * math.cos(math.pi * min(t / .018, 1))
        release = .5 - .5 * math.cos(math.pi * min((LENGTH - 1 - i) / (RATE * .065), 1))
        tone = (math.sin(2 * math.pi * 330 * t) * math.exp(-t / .17)
                + .14 * math.sin(2 * math.pi * 660 * t) * math.exp(-t / .09)
                + .025 * math.sin(2 * math.pi * 990 * t) * math.exp(-t / .055))
        result.append(round(16000 * attack * release * tone))
    return result


if __name__ == "__main__":
    pcm = samples()
    header = ROOT / "include/activation_dong.h"
    rows = [", ".join(str(v) for v in pcm[i:i+16]) for i in range(0, LENGTH, 16)]
    header.write_text("// Generated by tools/make_activation_dong.py. Original synthesized audio.\n"
                      "#pragma once\n#include <stdint.h>\n"
                      "static const int16_t activationDong[] PROGMEM = {\n    "
                      + ",\n    ".join(rows) + "\n};\n", encoding="utf-8")
    preview = ROOT / "assets/audio/activation-dong.wav"
    preview.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(preview), "wb") as output:
        output.setnchannels(1); output.setsampwidth(2); output.setframerate(RATE)
        # Quiet desktop audition. Board gain is separately capped in audio_engine.
        output.writeframes(struct.pack("<" + "h" * LENGTH, *(round(v * .16) for v in pcm)))
    shutil.copyfile(preview, ROOT / "preview/activation-dong.wav")
    assert pcm[0] == pcm[-1] == 0 and max(abs(v) for v in pcm) < 32767
    print(f"Generated {LENGTH/RATE:.3f}s dong; waveform peak {max(abs(v) for v in pcm)}; no clipping")
